//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumenty
    {
        public Nullable<System.DateTime> data_zlecenia { get; set; }
        public string oplacone { get; set; }
        public string przetlumaczone { get; set; }
        public string oddane_klientowi { get; set; }
        public int id_dokumentu { get; set; }
        public Nullable<int> id_klienta { get; set; }
        public Nullable<int> id_tlumacza { get; set; }
        public Nullable<int> id_jezyka_oryginalu { get; set; }
        public Nullable<int> id_jezyka_tlumaczenia { get; set; }
    
        public virtual Jezyki Jezyki { get; set; }
        public virtual Jezyki Jezyki1 { get; set; }
        public virtual Klienci Klienci { get; set; }
        public virtual Tlumacze Tlumacze { get; set; }
    }
}
