//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TranslatorsDBEntities : DbContext
    {
        public TranslatorsDBEntities()
            : base("name=TranslatorsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dokumenty> Dokumenties { get; set; }
        public virtual DbSet<Jezyki> Jezykis { get; set; }
        public virtual DbSet<Jezyki_Tlumacza> Jezyki_Tlumacza { get; set; }
        public virtual DbSet<Klienci> Kliencis { get; set; }
        public virtual DbSet<Tlumacze> Tlumaczes { get; set; }
    }
}
